#!/usr/bin/env bash
# install nginx server

sudo apt-get update -y
sudo apt-get install nginx -y
sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /etc/nginx/
echo "Holberton School" > /var/www/html/index.html
sudo service nginx restart
