#!/usr/bin/env bash
# Installing Nginx on Server and redirect
sudo apt-get update -y
sudo apt-get install -y nginx
sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /etc/nginx
echo "Holberton School" > /var/www/html/index.html
# add this line to server properperties
redirection="location /redirect_me { \
\t\treturn 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;\
\t\t}"
# path='/etc/nginx/sites-available/default'
# pattern='listen \[::\]:80'
#sudo sed -i "/$pattern/ a \ $redirection" $path
sudo sed -i "30i $redirection" /etc/nginx/sites-available/default
# restart service
sudo service nginx restart
