#!/usr/bin/env bash
# Configures ngnix server to have a custom 404 page containing the string
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School" > /var/www/html/index.nginx-debian.html
# create a custom page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
# add config to show custom_404 page 
NOTFOUND="error_page 404 /custom_404.html;\n location = /custom_404.html {\n root /usr/share/nginx/html;\n internal;\n}\n"
sudo sed -i "33i$NOTFOUND" /etc/nginx/sites-available/default
sudo service nginx restart