#!/usr/bin/env bash
# Configures ngnix server to have a custom 404 page containing the string
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
NOTFOUND="error_page 404 /custom_404.html;\n location = /custom_404.html {\n root /usr/share/nginx/html;\n internal;\n}\n"
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
sudo sed -i "33i$NOTFOUND" /etc/nginx/sites-available/default
sudo service nginx restart