#!/usr/bin/env bash
# write a custom header response

#install inginx
sudo apt-get update -y
sudo apt-get install nginx -y
sudo chown -R $"USER":$"USER" /var/www/
sudo chown -R $"USER":$"USER" /var/www/

# rewrite header response
export HOSTNAME=2140-web-1
path="/etc/nginx/sites-enabled/default"
pattern="location \/ {"
newinsert="add_header X-Served-By  $HOSTNAME;"
sed -ie "0,/$pattern/s//$pattern\n\t\t$newinsert/g" $path

# restart nginx web server
sudo service nginx restart
