#!/usr/bin/env bash
# config our haproxy
sudo apt-get -y update
sudo apt-get -y install haproxy

echo "ENABLED=1" >> /etc/default/haproxy
echo "
frontend http
  bind *:80
  mode http
  timeout client 60s
  default_backend web-backend

backend web-backend
   timeout connect 10s
   timeout server 100s
   mode http
   balance roundrobin
   server web1 34.75.197.138:80
   server web2 104.196.173.55:80
" > ~/newconf.cfg

sudo haproxy -f ~/newconf.cfg
