#!/usr/bin/env bash
# handle multiple trap 
path="/var/run/holbertonscript.pid"
pid=$$

echo "$pid" > $path

handle_int () {
	echo "Y U no love me?!"
}
handle_term () {
	echo "I hate the kill command"
	kill -9 "$pid"
	sudo rm -f "$path"
}
handle_quit () {
	kill -9 "$pid"
	sudo rm -f "$path"
}

trap handle_term SIGTERM
trap handle_int SIGINT
trap handle_quit SIGQUIT

while true; do
	echo "To infinity and beyond"
	sleep 1
done
