#!/usr/bin/env bash
# FizzBuzz exercise

i=1
while [[ $i -le 100 ]]; do
	if (( i % 3 == 0 ))
	then
		if (( i % 15 == 0 ));
		then
			echo "FizzBuzz "
		else
			echo "Fizz "
		fi
	elif (( i % 5 == 0 ));
	then
		if (( i % 15 == 0 ));
		then
			echo "FizzBuzz "
		elif (( i != 100 ))
		then
			echo "Buzz "
		else
			echo "Buzz"
		fi
	else
		echo "$i"
	fi
	(( i++ ))
done
