#!/usr/bin/env bash
# displays the content of the file /etc/passwd

filename="/etc/passwd"

managingLine ()
{
	firstArgument=$1
	IFS=':'     # hyphen (-) is set as delimiter
	# str is read into an array as tokens separated by IFS
	read -ra ADDR <<< "$firstArgument"
	newstring="The user ${ADDR[0]} is part of the ${ADDR[3]} gang, lives in ${ADDR[5]} and rides ${ADDR[6]}. ${ADDR[2]}'s place is protected by the passcode ${ADDR[1]}, more info about the user here: ${ADDR[4]}"
	echo "$newstring"
}

# read from file
n=1
while read -r line; do
	# reading each line
	managingLine "$line"
	n=$((n+1))
done < "$filename"
