#!/usr/bin/env bash
# create a new user (without password) and grant it all root privilage
username=nginx
# adduser $username --disabled-password --gecos "" --quiet

# chown -R "$username":"$username" /var/www

for pid in $(pidof apache2); do
    kill "$pid"
done

sed -i '1i  user nginx;\n' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

chown -R $username:$username /etc/nginx
chmod +rw /etc/nginx/nginx.conf
sudo service nginx restart -u "$username"
