#!/usr/bin/env bash
# create a new user (without password) and grant it all root privilage
username=nginx
# adduser $username --disabled-password --gecos "" --quiet

# chown -R "$username":"$username" /var/www
chown -R nginx:nginx /etc/nginx
chmod +rw /etc/nginx/nginx.conf
for pid in $(pidof apache2); do
    kill "$pid"
done

sed -i '1i  user nginx;\n' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo service nginx start -u "$username"
