#!/usr/bin/env bash
# create a new user (without password) and grant it all root privilage
pkill apache2 
# sudo sed -i '1i  user nginx;\n' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod +rw /etc/nginx/nginx.conf
# chown -R nginx:nginx /etc/nginx
su -c 'service nginx start' nginx
