#!/usr/bin/env bash
# create a new user (without password) and grant it all root privilage
pidof apache2 | xargs kill
sudo sed -i '1i  user nginx;\n' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chown -R nginx:nginx /etc/nginx
chmod +rw /etc/nginx/nginx.conf
su -c 'service nginx start' nginx
